sudo: required
services:
    - docker

before_install:
    - docker build -t ericsojohansson/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run ericsojohansson/react-test npm test -- --coverage

after_success:
    - docker build -t ericsojohansson/multi-client -f ./client
    - docker build -t ericsojohansson/multi-nginx -f ./nginx
    - docker build -t ericsojohansson/multi-server -f ./server
    - docker build -t ericsojohansson/multi-worker -f ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push ericsojohansson/multi-client
    - docker push ericsojohansson/multi-nginx
    - docker push ericsojohansson/multi-server
    - docker push ericsojohansson/multi-worker